Allow undo of article fragment remove
sonata-project/SonataArticleBundle pull request #118
Opened 2019-02-14 15:56 UTC by c-Rolland

## Subject

I am targeting this branch, because i propose a new article fragments deletion feature. This feature  move the removed fragment input's in another dom and this allows the cancellations of removed fragments. 

This feature fix too a bug of the removal of predefined fragments in the creation of new article. Bug detected at Ekino.

## Changelog

```markdown
### Added
- Added to fragmentList.jquery.js `moveSelectedFragmentOutsideOfForm()` to move selected fragment in tmp dom
- Added to fragmentList.jquery.js `cancelFragmentDeletion()`  to cancel the fragment deletion

### Changed
The 'removed' fragments are not removed completely just moved in another dom, 
which allows the cancellation. 
         
```
![](https://user-images.githubusercontent.com/26876221/52793128-49d86e00-306d-11e9-83bc-b05df828ee21.gif)

2019-02-14 16:44 UTC, mazsudo requested changes

2019-02-14 16:44 UTC, bmaziere commented on src/Resources/public/js/fragmentList.jquery.js
> +         * This method move the selected fragment and from elements in div#deletedFragments
`form elements` i guess ;)

2019-02-14 16:44 UTC, bmaziere commented on src/Resources/public/js/fragmentList.jquery.js
> +            // Insert the title of fragment and the reset button at the pace of removed fragment.
`Insert the fragment's title and the reset button in the place of removed fragment.`?

2019-03-06 11:04 UTC, c-Rolland commented
@bmaziere hello ^^ we need this changes at Ekino ^^ can you review the added code pls ? ^^

2019-03-06 11:16 UTC, core23 commented
Please run cs fixer

2019-03-06 11:27 UTC, OskarStark commented
@core23 the PHP CS issues should be fixed by a rebase

2019-03-06 11:28 UTC, OskarStark commented
I would appreciate some docs for this new feature, or at least a note in the documentation

2019-03-06 11:29 UTC, mazsudo requested changes

2019-03-06 11:29 UTC, bmaziere commented on src/Resources/public/js/fragmentList.jquery.js
> +            divElement.attr('id', 'deletedFragments');
think we should follow some kind of convention here ;) id should be hypens separated as mainly in sonata admin templates

2019-03-11 13:49 UTC, c-Rolland commented
> I would appreciate some docs for this new feature, or at least a note in the documentation

@OskarStark i can add it in witch doc file?

2019-03-20 08:26 UTC, bmaziere commented
any news on this @c-Rolland ? i guess you can add a new dedicated doc file as it is a new feature

2019-04-01 14:52 UTC, c-Rolland commented
@bmaziere the new doc file about the new feat its created .. can you check it pls ? ^^

2019-04-01 15:05 UTC, mazsudo requested changes

2019-04-01 15:05 UTC, bmaziere commented on docs/reference/article_fragment.rst
> +This feature move the removed fragment input's in another DOM and thereafter
moves

2019-04-01 15:05 UTC, bmaziere commented on docs/reference/article_fragment.rst
> +contain a reset button (to undo the deletion) and the fragment title. This action triggers undo of
contains

2019-04-01 15:05 UTC, bmaziere commented on docs/reference/article_fragment.rst
> +    This feature fix too a bug of the removal of predefined fragments in the creation of new article.
not sure this note is necessary as soon as the previous bug is resolved ;)

2019-04-01 15:05 UTC, bmaziere commented on docs/reference/article_fragment.rst
> +
this file should only concern fragment deletion so should be named delete_fragment.rst IMO. It has to be referenced in index.rst file (will fix a part of the build) (and you should rebase ;) will fix the second part of the build 
 i mean flintCI part)

2019-04-08 08:59 UTC, mazsudo submitted a review, later dismissed

2019-04-08 18:39 UTC, greg0ire commented on docs/reference/delete_fragment.rst
> +This feature moves the removed fragment input's in another DOM and thereafter
:thinking: should "input's" become "inputs"? same below

2019-04-08 18:39 UTC, greg0ire commented on src/Resources/public/js/fragmentList.jquery.js
> +         * This method cancel the fragment deletion.
```suggestion
         * This method cancels the fragment deletion.
```

2019-04-08 18:40 UTC, greg0ire commented on src/Resources/public/js/fragmentList.jquery.js
> -
Why did you remove this line?

2019-04-08 18:40 UTC, greg0ire commented on src/Resources/public/js/fragmentList.jquery.js
> +         * This method move the selected fragment and form elements in div#deleted-fragments
```suggestion
         * This method moves the selected fragment and form elements in div#deleted-fragments
```

2019-04-08 18:41 UTC, greg0ire commented on src/Resources/public/js/fragmentList.jquery.js
> +         * @param formElement
What is the purpose of these docblocks? Shouldn't there be types?

2019-05-16 09:39 UTC, mazsudo requested changes

2019-05-16 09:39 UTC, bmaziere commented on docs/reference/delete_fragment.rst
> +the deletion of the fragment so the moved fragment input's (and elements) are moving in their original place.
the deletion of the fragment so the deleted fragment inputs (and elements) are moved to their original place.

2019-05-28 10:17 UTC, mazsudo approved these changes

2019-06-03 18:04 UTC, greg0ire commented
@c-Rolland did you remove your repository or something? It says `unknown_repository` and I cannot use the code suggestion feature.

2019-12-11 14:19 UTC, c-Rolland commented
@greg0ire https://github.com/sonata-project/SonataArticleBundle/pull/140 ^^

2019-12-11 14:19 UTC, closed without merging