Better fragment data formatter
sonata-project/SonataArticleBundle pull request #136
Opened 2019-11-13 15:13 UTC by c-Rolland

## Subject

I am targeting this branch, because i have a little problem with the data format passed to the DOM who display the fragment's name and type. The little change format better the data passed to the DOM.

2019-11-13 18:25 UTC, greg0ire reviewed
I agree that the way you propose to do this looks better, but I would like to know what is this little problem you had exactly.

2019-11-13 18:25 UTC, greg0ire commented on src/Resources/views/FragmentAdmin/form.html.twig
> +         data-formdata="{{ formdata|json_encode() }}"
If the extra `formdata` is for clarity, here is another way to get some clarity: use linebreaks.
```suggestion
         data-formdata="{{ {
             'name': fragmentLabel ~ ' ' ~ fragmentName|escape, 
             'type' : form.vars.data.backofficeTitle|trans({}, 'SonataArticleBundle') 
         }|json_encode() }}"
```

2019-11-14 08:51 UTC, core23 requested changes

2019-11-14 08:51 UTC, core23 commented on src/Resources/views/FragmentAdmin/form.html.twig
> +    {% set formdata = {'name': fragmentLabel ~ ' ' ~ fragmentName|escape, 'type' : form.vars.data.backofficeTitle|trans({}, 'SonataArticleBundle') } %}
You can remove this

2019-11-14 08:54 UTC, c-Rolland commented
@greg0ire when i have special characters or html tags in "type" property nothing appears .. 
<img width="1178" alt="Capture d’écran 2019-11-13 à 15 44 52" src="https://user-images.githubusercontent.com/26876221/68841101-450c1d80-06c4-11ea-8d97-accc02b49da4.png">

i console.log the data given for jquery and when the "type" contains special characters or html tags we receive a string instead of a object ^^

2019-11-14 08:55 UTC, c-Rolland commented
I don't know  what's causing that but this change fix it ^^

2019-11-14 09:33 UTC, core23 approved these changes

2019-11-14 10:34 UTC, c-Rolland commented
i don't understand why the coverage fail i just modify a twig template ..

2019-11-14 11:05 UTC, OskarStark commented
> i don't understand why the coverage fail i just modify a twig template ..

We now have 3 code lines more, but no additional testing, so the percentage is lower. Don't worry :)

2019-11-14 11:05 UTC, OskarStark approved these changes

2019-11-14 11:08 UTC, merged

2019-11-14 11:46 UTC, c-Rolland commented
cool thanks .. ^^ @SonataCI can you tag this pls ? we need this fix in prod ^^

2019-11-14 12:24 UTC, core23 commented
SonataCI is a bot, so... No

But @sonata-project/release-managers can :+1:

2019-11-14 15:16 UTC, c-Rolland commented
my bad sorry XD