[FEAT/FRAGMENT]: Allow undo of article fragment remove && bug fix
sonata-project/SonataArticleBundle pull request #140
Opened 2019-12-11 14:18 UTC by c-Rolland

## Subject

I am targeting this branch, because i propose a new article fragments deletion feature. This feature  move the removed fragment input's in another dom and this allows the cancellations of removed fragments. 

This feature fix too a bug of the removal of predefined fragments in the creation of new article. Bug detected at Ekino.

## Changelog

```markdown
### Added
- Added to fragmentList.jquery.js `moveSelectedFragmentOutsideOfForm()` to move selected fragment in tmp dom
- Added to fragmentList.jquery.js `cancelFragmentDeletion()`  to cancel the fragment deletion

### Changed
The 'removed' fragments are not removed completely just moved in another dom, 
which allows the cancellation. 
         
```
![](https://user-images.githubusercontent.com/26876221/52793128-49d86e00-306d-11e9-83bc-b05df828ee21.gif)

2019-12-11 14:22 UTC, core23 commented on src/Resources/public/js/fragmentList.jquery.js
> +            //Removed the last element ?
```suggestion
            // Removed the last element ?
```

2019-12-11 14:22 UTC, core23 requested changes

2019-12-11 14:22 UTC, core23 commented on src/Resources/public/js/fragmentList.jquery.js
> +         * @param e
Can you please add a typehint

2019-12-11 14:30 UTC, core23 submitted a review, later dismissed

2019-12-11 14:31 UTC, c-Rolland commented
@core23 thanks ^^

2019-12-11 20:46 UTC, greg0ire commented on docs/reference/docs/reference/delete_fragment.rst
> +the deletion of the fragment so the deleted fragment inputs (and elements) are moved to their original place.
Please comply with the sf docs standards:

> [Each line should break approximately after the first word that crosses the 72nd character (so most lines end up being 72-78 characters);](http://symfony.com/doc/current/contributing/documentation/standards.html)

Also, the docs job fails in Travis, you can fix it by adding a reference to this page in `docs/index.rst`

2019-12-13 09:26 UTC, core23 approved these changes

2019-12-14 13:23 UTC, greg0ire approved these changes

2019-12-14 13:32 UTC, merged

2019-12-14 13:32 UTC, core23 commented
Thanks @c-Rolland

2019-12-14 13:51 UTC, greg0ire commented
https://github.com/sonata-project/SonataArticleBundle/releases/tag/1.3.0 :gift:

2019-12-14 14:38 UTC, c-Rolland commented
@greg0ire Thanks :DD