Add fragment backoffice title and improve validation
sonata-project/SonataArticleBundle pull request #22
Opened 2016-12-01 09:44 UTC by qsomazzi

## Changelog

```markdown
### Added
- Fragment "Backoffice title"

### Changed
- FragmentService `buildEditForm` now call `buildForm` to add backoffice title to each fragments
- FragmentService validate signature
```
## Subject

The goal of this PR is to handle new backoffice title for each fragments. This improve the readability of the admin, instead of seeing only the fragment type, you will see a label related to your content. Also, the validate signature was wrong, because it's called from the article admin.

2016-12-01 10:07 UTC, greg0ire commented on Resources/public/js/fragmentList.jquery.js
> +            if (!sure) {
This variable is used only once. Why not just write

```
if (!confirm("The fragment will be deleted after update. Are you sure?")) {
{
}
```

2016-12-01 10:07 UTC, greg0ire commented on Resources/public/js/fragmentList.jquery.js
> +            var sure = confirm("The fragment will be deleted after update. Are you sure?");
No i18n?

2016-12-02 08:26 UTC, qsomazzi commented
Hello @sonata-project/contributors, we really need this merge by the morning, can we merge it please ?

2016-12-02 08:36 UTC, qsomazzi commented
One required check can't be launched but i don't know why

2016-12-02 08:57 UTC, greg0ire commented
I'll talk to @Soullivaneuh about that

2016-12-02 08:58 UTC, qsomazzi commented
thanks @greg0ire

2016-12-02 09:00 UTC, greg0ire commented
BTW, shouldn't this be split into 2 commits? It looks like you are doing 2 separate things here.

2016-12-02 09:19 UTC, greg0ire commented
@Soullivaneuh unstuck StyleCI, but you have to force push to trigger it.

2016-12-02 09:26 UTC, greg0ire commented on FragmentService/AbstractFragmentService.php
> +        if (empty($object->getBackofficeTitle())) {
Isn't there a more Symfony-ish way of doing this, by using the `NotBlank` constraint?

2016-12-02 09:26 UTC, greg0ire commented on FragmentService/AbstractFragmentService.php
> +        if (empty($object->getBackofficeTitle())) {
Could save you some translations…

2016-12-02 09:42 UTC, qsomazzi commented on FragmentService/AbstractFragmentService.php
> +        if (empty($object->getBackofficeTitle())) {
the whole validation part is still a work in progress, for the moment we can't use symfony constraints, we are working on that on another PR. I will add the todo in doc.

2016-12-02 09:43 UTC, greg0ire commented on FragmentService/AbstractFragmentService.php
> +        if (empty($object->getBackofficeTitle())) {
ok

2016-12-02 10:02 UTC, qsomazzi commented
@greg0ire I've split it in 3 (to be more precise)

2016-12-02 10:10 UTC, greg0ire requested changes

2016-12-02 10:10 UTC, greg0ire commented on FragmentService/FragmentServiceInterface.php
> +    /**
Uuuh… what?

2016-12-02 10:10 UTC, greg0ire commented on Model/AbstractFragment.php
> +    protected $backofficeTitle;
Should be private

2016-12-02 10:10 UTC, greg0ire commented on Resources/views/FragmentAdmin/form.html.twig
> +    <div data-fragment-form="{{ form.vars.id }}" data-form-tmp="true" data-formdata='{ "name": "Fragment {{ fragmentName }}", "type": "{{ form.vars.data.backofficeTitle }}" }' data-errors="{{ form.va
Linebreak this please

2016-12-02 10:10 UTC, greg0ire commented on Resources/views/FragmentAdmin/form.html.twig
> +                    {% if form.vars.errors is defined and form.vars.errors|length > 0 %}
`form.vars.errors|default([])|lenght` would be shorter, but the best would be to have this variable always defined

2016-12-02 10:10 UTC, greg0ire commented on Resources/doc/reference/todo.rst
> +This bundle is still a work in progress, we need to work more on some part.
"parts"

2016-12-02 10:51 UTC, qsomazzi commented on Model/AbstractFragment.php
> +    protected $backofficeTitle;
can't set it private, all other properties are protected, and we used them (on fixtures for exemple)

2016-12-02 10:52 UTC, greg0ire commented on Model/AbstractFragment.php
> +    protected $backofficeTitle;
ok leave it as is then

2016-12-02 10:54 UTC, greg0ire commented on Resources/views/FragmentAdmin/form.html.twig
> +                    {% if form.vars.errors|default([])|lenght > 0 %}
Did you test this? Beware, this is a trick question…

2016-12-02 10:55 UTC, qsomazzi commented on Resources/views/FragmentAdmin/form.html.twig
> +                    {% if form.vars.errors|default([])|lenght > 0 %}
honestly no, i've trust your knowledge :) will do give me 2min :p

2016-12-02 10:56 UTC, greg0ire commented on Resources/views/FragmentAdmin/form.html.twig
> +                    {% if form.vars.errors|default([])|lenght > 0 %}
Good answer ;) I mispellt `length`, and you copied it, that's why I'm asking

2016-12-02 13:10 UTC, qsomazzi commented on Resources/views/FragmentAdmin/form.html.twig
> +                    {% if form.vars.errors|default([])|lenght > 0 %}
@greg0ire all good now :)

2016-12-02 13:10 UTC, greg0ire approved these changes

2016-12-02 13:11 UTC, greg0ire commented
@sonata-project/contributors , please review and merge

2016-12-02 14:48 UTC, rande approved these changes

2016-12-02 14:48 UTC, rande commented on Resources/public/js/fragmentList.jquery.js
> +            console.log('[Sonata.Admin] [fragments|add] current index is ' + this._elementsIndex);
``Admin.log`` and not ``console.log``

2016-12-02 15:06 UTC, merged

2017-03-23 09:50 UTC, OskarStark commented
I mark these PR as `minor` instead of major, as there is no current release