Fix setTags type on article setter
sonata-project/SonataArticleBundle pull request #31
Opened 2017-01-31 10:08 UTC by qsomazzi

## Changelog

```markdown
### Changed
 - Update Article tags setter param type to be array 
```

## Subject

The goal of this PR is to fix the article tags setter to be an array. This allow fixtures to be implemented.

2017-01-31 10:15 UTC, greg0ire commented on Model/AbstractArticle.php
> +    public function setTags(array $tags = null)
I think you can remove the `use` statement.

2017-01-31 10:15 UTC, greg0ire requested changes

2017-01-31 10:15 UTC, greg0ire commented on Model/ArticleInterface.php
>       * @return Tag[]|Collection $tags
This should be changed, right?

2017-01-31 10:45 UTC, qsomazzi commented on Model/AbstractArticle.php
> +    public function setTags(array $tags = null)
done

2017-01-31 10:48 UTC, greg0ire commented on Model/AbstractArticle.php
> +    public function setCategories(ArrayCollection $categories = null)
I didn't notice that one. I don't think you should change to `ArrayCollection`, b/c it's better to type hint against an interface.

2017-01-31 11:03 UTC, qsomazzi commented
@greg0ire all done :)

2017-01-31 11:04 UTC, greg0ire commented on Model/AbstractArticle.php
> +     * @var ArrayCollection
Did you mean `array`?

2017-01-31 11:04 UTC, qsomazzi commented on Model/AbstractArticle.php
> +     * @var ArrayCollection
no, It's still an ArrayCollection, just the setter change for the fixtures

2017-01-31 11:06 UTC, greg0ire commented on Model/AbstractArticle.php
> +     * @var ArrayCollection
oh ok. Doctrine has its own magic to hydrate that IIRC, indeed

2017-01-31 11:06 UTC, greg0ire approved these changes

2017-01-31 11:06 UTC, merged

2017-03-23 09:50 UTC, OskarStark commented
I mark these PR as `minor` instead of major, as there is no current release