Refactor folder structure
sonata-project/SonataArticleBundle pull request #56
Opened 2017-10-19 15:30 UTC by core23

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Changed
 - Changed internal folder structure to `src`, `tests` and `docs`
```

## Subject

Adopt the new folder structure discussed on the [dev-kit](https://github.com/sonata-project/dev-kit/issues/278)

2017-10-27 12:03 UTC, OskarStark requested changes
Please fix travis

2017-11-04 09:02 UTC, core23 commented
Travis looks okay @OskarStark

2017-11-05 10:49 UTC, greg0ire approved these changes

2017-11-06 07:41 UTC, OskarStark approved these changes

2017-11-06 07:41 UTC, merged